---
apiVersion: platform.confluent.io/v1beta1
kind: Zookeeper
metadata:
  name: zookeeper
  namespace: confluent
spec:
  configOverrides:
    server:
    - auto.create.topics.enable=true
    - default.replication.factor=2
    - offsets.topic.replication.factor=2
    - min.insync.replicas=1
  podTemplate:
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
              - confluent-demo
  replicas: 1
  image:
    application: confluentinc/cp-zookeeper:7.4.0
    init: confluentinc/confluent-init-container:2.6.0
  dataVolumeCapacity: 10Gi
  logVolumeCapacity: 10Gi
---
apiVersion: platform.confluent.io/v1beta1
kind: Kafka
metadata:
  name: kafka
  namespace: confluent
  labels:
    foo: broker
spec:
  configOverrides:
    server:
    - auto.create.topics.enable=true
    - default.replication.factor=2
    - offsets.topic.replication.factor=2
    - min.insync.replicas=1
  podTemplate:
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: foo.service
              operator: In
              values:
              - broker
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            labelSelector:
              matchExpressions:
              - key: foo
                operator: In
                values:
                - broker
            topologyKey: "kubernetes.io/hostname"
  replicas: 2
  image:
    application: confluentinc/cp-server:7.4.0
    init: confluentinc/confluent-init-container:2.6.0
  dataVolumeCapacity: 10Gi
  metricReporter:
    enabled: true
  dependencies:
    zookeeper:
      endpoint: zookeeper.confluent.svc.cluster.local:2181
---
apiVersion: platform.confluent.io/v1beta1
kind: ControlCenter
metadata:
  name: controlcenter
  namespace: confluent
spec:
  configOverrides:
    server:
    - replication.factor=2
    - confluent.controlcenter.internal.topics.replication=2
    - confluent.controlcenter.internal.topics.partitions=2
    - confluent.metrics.topic.replication=2
    - confluent.metrics.topic.partitions=2
    - confluent.monitoring.interceptor.topic.replication=2
    - confluent.monitoring.interceptor.topic.partitions=2
    - confluent.controlcenter.command.topic.replication=2
    - confluent.controlcenter.command.topic.partitions=2
    - confluent.controlcenter.command.topic=_confluent_command
  podTemplate:
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
              - confluent-demo
  replicas: 1
  image:
    application: confluentinc/cp-enterprise-control-center:7.4.0
    init: confluentinc/confluent-init-container:2.6.0
  dataVolumeCapacity: 10Gi
  dependencies:
    schemaRegistry:
      url: http://schemaregistry.confluent.svc.cluster.local:8081
    ksqldb:
    - name: ksqldb
      url: http://ksqldb.confluent.svc.cluster.local:8088
    connect:
    - name: connect
      url: http://connect.confluent.svc.cluster.local:8083